### ISSUE TITLE
请求添加带密码房间的入会功能！

### ISSUE THREAD

**Issue by C029s-MOC** [SummerFoam233/Tencent-AutoMeeting#1]
需要托管的房间基本上都有密码，跪求添加自动输入密码功能！

**Comment by SummerFoam233** [comment]
你好，感谢使用，密码入会功能已增加，但由于seleium库不支持对安全控件(input password等)进行send_key操作，因此我引入了pyautogui库进行模拟键盘输入完成密码的输入，带来的问题是密码输入时浏览器必须在前台，无法实现全程的后台操作，后续有时间我会寻找改善方法。
